services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-front
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://host.docker:2375
